### ISSUE TITLE
Weird behaviour "Relationship method must return an object"

### ISSUE THREAD

**Issue by okaufmann** [ThisVessel/Carbonated#4]
Hi

I've got a weird problem where Eloquent want's to resolve carbonated Properties as Relations.

If I have a Model like this:

``` php
class MovieRating extends Model
{
    use Carbonated;

    protected $fillable = ['users_id', 'property_2', 'property_3'];

    public $carbonatedTimestamps = ['created_at', 'updated_at'];
    public $carbonatedDates = [];
    public $carbonatedTimes = [];
    public $databaseTimezone = 'UTC';
    public $carbonatedTimezone = 'America/Toronto';
    public $databaseTimestampFormat = 'Y-m-d H:i:s';
    public $databaseDateFormat = 'Y-m-d';
    public $databaseTimeFormat = 'H:i:s';
    public $jsonTimezone = 'UTC';
    public $carbonatedTimestampFormat = 'Y-m-d\TH:i:sP';
}
```

Everything works just fine. But if I don't need one of them (cause I'm happy with the defaults or so) the following error will be thrown (Here the property `$carbonatedTimestamps`):
![image](https://cloud.githubusercontent.com/assets/4414498/16749435/723dea3e-47ca-11e6-84b3-11005ee8c4db.png)

This worked a long time but suddenlty no longer? Do you have an Idea? I'm running of ideas.... "-_-

**Comment by JesseLeite** [comment]
Hmm weird.  I'll take a look.

**Comment by okaufmann** [comment]
Fixed in in my own fork.
